### ISSUE TITLE
How to use the opacity variant?

### ISSUE THREAD

**Issue by Leravig** [crswll/tailwindcss-theme-swapper#10]
Hey, I tried to use your variant with the opacity for the colors. But I don't get it to work.

`error  in ./src/assets/styles/tailwind.css
Syntax Error: TypeError: value.charCodeAt is not a function`

Setup:
Tailwindcss 2.0.3 (tried it with 2.0.2)
Postcss: latest (tried it with the versions 7.0.35 and 8.0.0)

**Comment by crswll** [comment]
Can you provide a little more detail? A config should do the trick. If possible posting it here would be really nice: https://play.tailwindcss.com/XbeJ1IvcSW?file=config

**Comment by Leravig** [comment]
Found the problem:
https://play.tailwindcss.com/JTAOA2JZ0V?file=config

I use the plugin [`flattenColorPalette`](https://github.com/tailwindlabs/tailwindcss/blob/master/src/util/flattenColorPalette.js)

Using it without the themeSwapper I get the following colors
```
primary: '#foo'
secondary: '#
```

and with it it looks like this
```
primary: [Function (anonymous)],
secondary: [Function (anonymous)],
```

**Comment by crswll** [comment]
So, the issue isn't `flattenColorPalette` I don't think, it's that css-in-js doesn't know what to do with the function that `borderLeftColor` is getting. You can call it, if it's a function, with the color proper variable.

So you can do like:

```js
  const resolveColor = (maybeFunction) =>
    typeof maybeFunction === 'function'
      ? maybeFunction({ opacityVariable: '--tw-border-opacity' })
      : maybeFunction
 ```
 
Here's it goes working: https://play.tailwindcss.com/eNm42UuZSS?file=config

**Comment by Leravig** [comment]
Hey, it works pretty fine. Thank you for your help
