### ISSUE TITLE
JIT support

### ISSUE THREAD

**Issue by TomDeSmet** [crswll/tailwindcss-theme-swapper#11]
This plugin doesn't seem to work with the new JIT compiler.
Any ideas how to make this work?

**Comment by crswll** [comment]
@TomDeSmet I use it with JIT. Any particular use case you're hitting issues with?

**Comment by TomDeSmet** [comment]
Not really, I have a basic setup and added some themes which all have a colors object with 3 colors in them.
I added the corresponding classes to my templates.
If I disable JIT it works, but when I use JIT mode, the colors of my themes don't appear, instead the base colors (from :root) are used.

I'm using Tailwind 2.1.1 and Theme Swapper 0.3.0 in a Webpack 5 setup.

**Comment by crswll** [comment]
If you can produce it in a repro I'll take a look. Are you doing anything like `bg-${dynamic}`? That's the only thing I can see working only when jit is off.

**Comment by TomDeSmet** [comment]
I'm outputting it through my CMS (via Twig) but as a complete variable `{{ themeClassName }}`, so the css class is server side rendered into the template as a whole.

**Comment by crswll** [comment]
`jit` has to scan files and actually see the class used in your code.

You'd need to list the `safelist.txt` file in your purge array for that to work. Willing to bet when you do that it'll work.

**Comment by TomDeSmet** [comment]
Thanks man! Speedy and great support :)
