### ISSUE TITLE
official tailwind typography/forms support.

### ISSUE THREAD

**Issue by mpalpha** [crswll/tailwindcss-theme-swapper#12]
How do I use this with tailwindcss-typography and tailwindcss-forms?

**Comment by crswll** [comment]
If you look at the source code for`tailwindcss-typography` you'll see lots of look ups with `theme` in [src/styles.js](https://github.com/tailwindlabs/tailwindcss-typography/blob/master/src/styles.js). It seems you'd need to create your own `gray` colors in the swapper to get it to work (unless you wanted to [customize everything yourself](https://github.com/tailwindlabs/tailwindcss-typography#customization) which kind of defeats the purpose.

Here is a dog shit ugly example with a few of the "gray" keys added to theme swapper: https://play.tailwindcss.com/TjuAhL2eqK?file=config (there's a "dark" theme **under** the regular one)

As for **forms**, it's [a very similar situation](https://github.com/tailwindlabs/tailwindcss-forms/blob/master/src/index.js). It seems like creating your own gray color scale will make it all work.

**Comment by crswll** [comment]
If you'd like anymore help with this feel free to open back up!
