### ISSUE TITLE
how to use the swapper

### ISSUE THREAD

**Issue by drtobbyas** [crswll/tailwindcss-theme-swapper#2]
Do you mind sharing how to apply theme swapper to a nuxt.js website or rather provide link to source of the demo so that I can get some hint from there?

**Comment by crswll** [comment]
Awesome idea. Here goes a link to the demo: https://github.com/crswll/tailwindcss-theme-swapper-example

Not sure I'm a good person to help with anything Nuxt related directly.

**Comment by crswll** [comment]
Closing this. If you need anything else feel free to reach out!

**Comment by Leravig** [comment]
Thank you for the late response, works fine. Tanks
