### ISSUE TITLE
screens doesn't seem to be working

### ISSUE THREAD

**Issue by harbolaez** [crswll/tailwindcss-theme-swapper#23]
the `screens` config doesn't seem to be working when applied through the theme swapper. 

i.e. https://play.tailwindcss.com/oBhl7HJKuG?file=config

**Comment by crswll** [comment]
Hello!

The screen would need to be in Tailwind's theme like this: https://play.tailwindcss.com/SYhD06VJw7

**Comment by harbolaez** [comment]
Thanks, @crswll, just saw the css does not support them. thanks!
