### ISSUE TITLE
Bug with boxShadow and some properties

### ISSUE THREAD

**Issue by mickael-poulachon** [crswll/tailwindcss-theme-swapper#29]
If i want override boxShadow properties like : 

- DEFAULT ,  lg ,layout 

Only if this class has used in html :o (like shadow-lg )

if i rename shadow-lg to shadow-test

then lg to test , bug to.

the build bug then my container and lot of other properties doesn't work

My theme : 

`{
          name: 'base',
          selectors: [':root'],
          theme: {
              boxShadow: {
                xs: '0px 0px 0px 1px rgba(0, 0, 0, 0.05)',
                sm: '0px 1px 2px rgba(0, 0, 0, 0.05)',
                base: '0px 1px 3px rgba(0, 0, 0, 0.1), 0px 1px 2px rgba(0, 0, 0, 0.06)',
                md: '0px 4px 6px -1px rgba(0, 0, 0, 0.1), 0px 2px 4px -1px rgba(0, 0, 0, 0.06)',
                lg: '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
                xl: '0px 20px 25px -5px rgba(0, 0, 0, 0.1), 0px 10px 10px -5px rgba(0, 0, 0, 0.04)',
                card: '0px 4px 15px -3px rgba(0, 0, 0, 0.1), 0px 4px 6px -2px rgba(0, 0, 0, 0.05)',
                none: 'none'
              },
            },
        },`
        
        after investigation any boxShadow style generated is like : 
        
![Capture d’écran 2022-05-11 à 15 36 59](https://user-images.githubusercontent.com/11704008/167863213-b89d1f4f-6d86-4c0d-a3ab-e876a35a5158.png)

**Comment by crswll** [comment]
I'm having a hard time following your situation.

I set up a demo similar to what I think you're doing and it appears to be working well: https://play.tailwindcss.com/mZBzcJXRYA?file=config

Can you replicate the issue there and then share the link in the event I missed something?

**Comment by mickael-poulachon** [comment]
Hi , yes i have find it on version 3.0.23 of tailwindcss,

After a update with same version of you 3.0.23, that working !

Thank's for your work !

Le mer. 11 mai 2022 à 21:24, Bill Criswell ***@***.***> a
écrit :
