### ISSUE TITLE
Theme doesn’t get applied to programmatic popovers

### ISSUE THREAD

**Issue by heymartinadams** [crswll/tailwindcss-theme-swapper#43]
Hi there ☺️

For some reason, `tailwindcss-theme-swapper` doesn’t seem to be applying the theme on popovers that are created programmatically (for example, a [datetime picker popover](https://mantine.dev/dates/date-time-picker/)).

In the DOM, the popover creates a new component that lives outside NextJS’ `<div id="_next">`.
![CleanShot 2023-10-25 at 11 53 37@2x](https://github.com/crswll/tailwindcss-theme-swapper/assets/11673745/4778b22f-6ec7-4d69-bcf3-97d8ffd273fc)

Even if I wrap the component in my theme...
![CleanShot 2023-10-25 at 11 55 12@2x](https://github.com/crswll/tailwindcss-theme-swapper/assets/11673745/e9e1b0dd-f1c0-4c3e-a34f-7a95476f462b)

...it doesn’t apply to the popover.
![CleanShot 2023-10-25 at 11 55 44@2x](https://github.com/crswll/tailwindcss-theme-swapper/assets/11673745/df804b58-d298-4395-8f0c-6650d38fd3a8)

How can this be fixed?

**Comment by crswll** [comment]
Tailwind CSS can't see a classname like `theme_${foo}_${bar}`. If you replace that with something hardcoded it should work. You can also consider applying the class that sets the theme on `<body>` or `<html>` so it'll scope the portals as well. If I'm still missing a reproduction where I can see more code can help.

**Comment by heymartinadams** [comment]
I figured it out by adding this class via a `useEffect`:

```js
useEffect(() => {
  document.body.classList.add(`theme_${appTheme?.brand}_${appTheme?.tint}`)
}, [appTheme])
```

Many thanks ✨
