### ISSUE TITLE
Safari 15 support, color-mix over RGB

### ISSUE THREAD

**Issue by OlegLustenko** [crswll/tailwindcss-theme-swapper#51]
Hi there! Thanks for creating a beautiful package!

## Description
In the past there was a PR Use color-mix over translating color to RGB #47

And we got an issue with Safari 15 support 

![image](https://github.com/crswll/tailwindcss-theme-swapper/assets/11524061/26c44e04-d0ca-41fd-836e-cb9818820e3a)
ref: https://caniuse.com/?search=%20color-mix

## Question
Is it possible to keep Safari 15 compatibilities? Or make this setting configurable?
Otherwise, we'll have to jump to older version

**Comment by crswll** [comment]
I'm so sorry completely missed this. You may just want to stick to an older version for now. I will add an option for older Safari if I make any big adjustments but with Tailwind 4 coming a lot of what this plugin does is now kind of built in.
