### ISSUE TITLE
color used for fill

### ISSUE THREAD

**Issue by xabatar** [crswll/tailwindcss-theme-swapper#52]
Without the plugin we can use fill-color in Tailwind and the system will generate css like: 
`.fill-color { fill: #b9d7fd; }`
But using the plugin for the same color will result in the following css entry: 
`.fill-color { fill: color-mix(in srgb,var(--colors-color),#0000 0); }`  
where the --colors-color variable is #b9d7fd;
The resulting color is a mix between black and the variable color, which is not the expected result.
It should output the simple color as the fill and not use color-mix. Or if it can't be done without color mix, then the mixing color should be white and not black.

**Comment by crswll** [comment]
That looks like it's being minified by something and that's causing issues. Do you know what it's being minified by?

https://play.tailwindcss.com/xBaMPVhPtJ
![Screenshot 2024-05-04 at 9 44 58 AM](https://github.com/crswll/tailwindcss-theme-swapper/assets/182222/f7608b3e-5c97-465a-9f8f-f3a5e5c57922)

**Comment by crswll** [comment]
I created #53 to see if that helps with the minification issue (if it is a minification issue). Want to make sure here first.

**Comment by xabatar** [comment]
You are right. Is a minifying issue.
I use VS Code with Tailwind installed with npm, and run the task with:
"npx tailwindcss -i ./pricing/Content/css/dex-style-source.css -o ./pricing/Content/css/style.css --watch --minify"

I I take out the minifying command the issue is gone.

I presume I use the command use the VS Code built in minifyer.
